#!/usr/bin/env -S NODE_PATH=/Users/fancn/2022/node/0_212_CLI/node_modules ESM_OPTIONS='{mode:"auto",cache:0}' node -r esm -r globals

if (!$1) {
  throw new Error("no arguments provided!");
}

// https://github.com

console.log($1);

const response = await fetch($1);

const data = await response.text();

console.log(data);
